// AUTO-GENERATED by scripts/blog/generate-content-bundles.mjs
// Do not edit manually. Re-run `node scripts/blog/generate-content-bundles.mjs`
// after adding/removing files in client/src/data/blog-content/<lang>/.
//
// One bundle per language. Keys are the canonical Spanish slug. Values are the
// raw markdown string of the localized article. Used by server/static.ts to
// emit a localized SEO prerender for crawlers per <html lang> URL.

import c0 from './ca/amazon-ecommerce-llc-vender-online';
import c1 from './ca/auditoria-rapida-llc-12-puntos-30-minutos';
import c2 from './ca/autonomo-espana-vs-llc-estados-unidos';
import c3 from './ca/autonomos-espana-por-que-dejar-de-serlo';
import c4 from './ca/bancos-vs-fintech-llc-donde-abrir-cuenta';
import c5 from './ca/boe-febrero-2020-llc-doctrina-administrativa';
import c6 from './ca/boi-report-fincen-guia-completa-2026';
import c7 from './ca/bookkeeping-llc-paso-a-paso';
import c8 from './ca/cambiar-divisas-llc-mejores-opciones';
import c9 from './ca/cambiar-proveedor-mantenimiento-llc-sin-perder-antiguedad';
import c10 from './ca/caminos-legales-minimos-impuestos';
import c11 from './ca/como-disolver-cerrar-llc-paso-a-paso';
import c12 from './ca/como-obtener-itin-numero-fiscal-irs';
import c13 from './ca/como-operar-llc-dia-a-dia';
import c14 from './ca/constituir-llc-proceso-paso-a-paso';
import c15 from './ca/convenio-doble-imposicion-usa-espana-llc';
import c16 from './ca/crear-empresa-andorra-ventajas';
import c17 from './ca/criptomonedas-trading-llc-impuestos';
import c18 from './ca/crs-2-0-carf-por-que-usa-no-firmara-llc';
import c19 from './ca/crs-cuentas-bancarias-llc-intercambio-informacion';
import c20 from './ca/crs-residentes-espana-latam-implicaciones';
import c21 from './ca/cuanto-cuesta-constituir-llc';
import c22 from './ca/cuenta-bancaria-mercury-llc-extranjero';
import c23 from './ca/cuentas-bancarias-usa-reportan-hacienda-verdad';
import c24 from './ca/cuota-autonomo-2026';
import c25 from './ca/cuotas-autonomos-2026-guia-completa';
import c26 from './ca/dac7-plataformas-digitales-reporting-2026';
import c27 from './ca/dac8-criptomonedas-reporting-fiscal-2026';
import c28 from './ca/diferencia-llc-corporation-s-corp-c-corp';
import c29 from './ca/diseno-estructura-fiscal-internacional-solida';
import c30 from './ca/documentar-separacion-fondos-llc-historial';
import c31 from './ca/documentos-llc-cuales-necesitas';
import c32 from './ca/dubai-uae-mito-no-impuestos';
import c33 from './ca/due-diligence-bancario-llc-americana';
import c34 from './ca/ein-numero-fiscal-llc-como-obtenerlo';
import c35 from './ca/empresa-bulgaria-10-tributacion';
import c36 from './ca/empresa-panama-fiscalidad-residencia';
import c37 from './ca/empresa-reino-unido-uk-ltd';
import c38 from './ca/errores-criticos-llc-ya-constituida';
import c39 from './ca/errores-fiscales-freelancers-espanoles';
import c40 from './ca/escalar-negocio-digital-llc-americana';
import c41 from './ca/estructura-fiscal-optima-freelancer-internacional';
import c42 from './ca/estructura-offshore-beneficios-riesgos';
import c43 from './ca/evitar-bloqueos-mercury-wise-revolut';
import c44 from './ca/exit-tax-espana-llc-cripto-interactive-brokers';
import c45 from './ca/extension-irs-form-1120-como-solicitarla';
import c46 from './ca/facturar-sin-ser-autonomo-alternativas-2026';
import c47 from './ca/fiscalidad-estonia-como-funciona';
import c48 from './ca/fiscalidad-internacional-emprendedores-digitales';
import c49 from './ca/fiscalidad-llc-por-pais-residencia';
import c50 from './ca/fiscalidad-socios-llc-cambio-residencia-mid-year';
import c51 from './ca/form-5472-que-es-como-presentarlo';
import c52 from './ca/gastos-deducibles-autonomos-2026';
import c53 from './ca/gastos-deducibles-llc-que-puedes-deducir';
import c54 from './ca/holding-empresarial-como-funciona';
import c55 from './ca/hong-kong-offshore-realidad';
import c56 from './ca/iban-swift-routing-number-que-son';
import c57 from './ca/impuestos-clientes-internacionales-espana';
import c58 from './ca/irs-1120-5472-que-son-cuando-aplican';
import c59 from './ca/itin-ssn-que-son-como-obtenerlos';
import c60 from './ca/iva-intracomunitario-servicios-europa';
import c61 from './ca/iva-servicios-digitales-internacional';
import c62 from './ca/justificar-origen-fondos-kyc-bancario-segunda-ronda';
import c63 from './ca/llc-agencias-marketing-digital';
import c64 from './ca/llc-alternativa-autonomo-espana';
import c65 from './ca/llc-creadores-contenido-youtube-twitch';
import c66 from './ca/llc-desarrolladores-software-saas';
import c67 from './ca/llc-estados-unidos-guia-completa-2026';
import c68 from './ca/llc-interactive-brokers-invertir-bolsa-usa';
import c69 from './ca/llc-no-paga-impuestos-eeuu-que-pasa-en-tu-pais';
import c70 from './ca/llc-seguridad-juridica-proteccion-patrimonial';
import c71 from './ca/llc-unica-estructura-holding-cuando-como-cuesta';
import c72 from './ca/mantenimiento-anual-llc-obligaciones';
import c73 from './ca/modelo-720-721-residentes-espana-cuentas-cripto-extranjero';
import c74 from './ca/modulos-vs-estimacion-directa-2026';
import c75 from './ca/nomada-digital-residencia-fiscal';
import c76 from './ca/nuevo-mexico-vs-wyoming-vs-delaware';
import c77 from './ca/operating-agreement-llc-que-es';
import c78 from './ca/pagar-cero-impuestos-legalmente-llc';
import c79 from './ca/pasarelas-pago-llc-stripe-paypal-dodo';
import c80 from './ca/por-que-abrir-llc-estados-unidos-ventajas';
import c81 from './ca/por-que-no-abrir-empresa-estonia';
import c82 from './ca/prevencion-blanqueo-capitales-llc';
import c83 from './ca/primer-mes-llc-que-esperar';
import c84 from './ca/privacidad-llc-americana-secreto-ventaja';
import c85 from './ca/problemas-comunes-llc-como-evitarlos';
import c86 from './ca/que-es-irs-guia-duenos-llc';
import c87 from './ca/que-pasa-si-no-presentas-5472-multas-irs';
import c88 from './ca/recuperar-llc-boi-5472-atrasados-procedimiento';
import c89 from './ca/registered-agent-que-es-por-que-necesitas';
import c90 from './ca/reorganizar-banca-llc-mercury-relay-wise';
import c91 from './ca/residentes-no-residentes-llc-diferencias';
import c92 from './ca/retenciones-irpf-factura';
import c93 from './ca/revolut-business-crs-reporting-fiscal';
import c94 from './ca/riesgos-fiscales-mala-estructuracion-internacional';
import c95 from './ca/separar-dinero-personal-llc-por-que-importa';
import c96 from './ca/single-member-multi-member-llc-implicaciones-fiscales';
import c97 from './ca/sociedad-limitada-espana-costes-ventajas';
import c98 from './ca/tengo-llc-checklist-gestion-correcta';
import c99 from './ca/testaferros-prestanombres-llc-ilegal-riesgos';
import c100 from './ca/tiempos-pagos-ach-wire-transfer';
import c101 from './ca/tramos-irpf-2026';
import c102 from './ca/tributacion-llc-segun-actividad-economica';
import c103 from './ca/tributacion-pass-through-llc-como-funciona';
import c104 from './ca/vender-o-cerrar-llc-comparativa-practica';
import c105 from './ca/ventajas-desventajas-llc-no-residentes';
import c106 from './ca/visa-mastercard-reporting-tarjetas-hacienda';
import c107 from './ca/w8-ben-y-w8-ben-e-guia-completa';
import c108 from './ca/wise-bancos-llc-stack-bancaria-completa';
import c109 from './ca/wise-business-crs-reporting-fiscal';
import c110 from './ca/wise-business-llc-guia';
import c111 from './ca/wise-iban-llc-que-reporta-hacienda';

export const BLOG_CONTENT_CA: Record<string, string> = {
"amazon-ecommerce-llc-vender-online": c0,
"auditoria-rapida-llc-12-puntos-30-minutos": c1,
"autonomo-espana-vs-llc-estados-unidos": c2,
"autonomos-espana-por-que-dejar-de-serlo": c3,
"bancos-vs-fintech-llc-donde-abrir-cuenta": c4,
"boe-febrero-2020-llc-doctrina-administrativa": c5,
"boi-report-fincen-guia-completa-2026": c6,
"bookkeeping-llc-paso-a-paso": c7,
"cambiar-divisas-llc-mejores-opciones": c8,
"cambiar-proveedor-mantenimiento-llc-sin-perder-antiguedad": c9,
"caminos-legales-minimos-impuestos": c10,
"como-disolver-cerrar-llc-paso-a-paso": c11,
"como-obtener-itin-numero-fiscal-irs": c12,
"como-operar-llc-dia-a-dia": c13,
"constituir-llc-proceso-paso-a-paso": c14,
"convenio-doble-imposicion-usa-espana-llc": c15,
"crear-empresa-andorra-ventajas": c16,
"criptomonedas-trading-llc-impuestos": c17,
"crs-2-0-carf-por-que-usa-no-firmara-llc": c18,
"crs-cuentas-bancarias-llc-intercambio-informacion": c19,
"crs-residentes-espana-latam-implicaciones": c20,
"cuanto-cuesta-constituir-llc": c21,
"cuenta-bancaria-mercury-llc-extranjero": c22,
"cuentas-bancarias-usa-reportan-hacienda-verdad": c23,
"cuota-autonomo-2026": c24,
"cuotas-autonomos-2026-guia-completa": c25,
"dac7-plataformas-digitales-reporting-2026": c26,
"dac8-criptomonedas-reporting-fiscal-2026": c27,
"diferencia-llc-corporation-s-corp-c-corp": c28,
"diseno-estructura-fiscal-internacional-solida": c29,
"documentar-separacion-fondos-llc-historial": c30,
"documentos-llc-cuales-necesitas": c31,
"dubai-uae-mito-no-impuestos": c32,
"due-diligence-bancario-llc-americana": c33,
"ein-numero-fiscal-llc-como-obtenerlo": c34,
"empresa-bulgaria-10-tributacion": c35,
"empresa-panama-fiscalidad-residencia": c36,
"empresa-reino-unido-uk-ltd": c37,
"errores-criticos-llc-ya-constituida": c38,
"errores-fiscales-freelancers-espanoles": c39,
"escalar-negocio-digital-llc-americana": c40,
"estructura-fiscal-optima-freelancer-internacional": c41,
"estructura-offshore-beneficios-riesgos": c42,
"evitar-bloqueos-mercury-wise-revolut": c43,
"exit-tax-espana-llc-cripto-interactive-brokers": c44,
"extension-irs-form-1120-como-solicitarla": c45,
"facturar-sin-ser-autonomo-alternativas-2026": c46,
"fiscalidad-estonia-como-funciona": c47,
"fiscalidad-internacional-emprendedores-digitales": c48,
"fiscalidad-llc-por-pais-residencia": c49,
"fiscalidad-socios-llc-cambio-residencia-mid-year": c50,
"form-5472-que-es-como-presentarlo": c51,
"gastos-deducibles-autonomos-2026": c52,
"gastos-deducibles-llc-que-puedes-deducir": c53,
"holding-empresarial-como-funciona": c54,
"hong-kong-offshore-realidad": c55,
"iban-swift-routing-number-que-son": c56,
"impuestos-clientes-internacionales-espana": c57,
"irs-1120-5472-que-son-cuando-aplican": c58,
"itin-ssn-que-son-como-obtenerlos": c59,
"iva-intracomunitario-servicios-europa": c60,
"iva-servicios-digitales-internacional": c61,
"justificar-origen-fondos-kyc-bancario-segunda-ronda": c62,
"llc-agencias-marketing-digital": c63,
"llc-alternativa-autonomo-espana": c64,
"llc-creadores-contenido-youtube-twitch": c65,
"llc-desarrolladores-software-saas": c66,
"llc-estados-unidos-guia-completa-2026": c67,
"llc-interactive-brokers-invertir-bolsa-usa": c68,
"llc-no-paga-impuestos-eeuu-que-pasa-en-tu-pais": c69,
"llc-seguridad-juridica-proteccion-patrimonial": c70,
"llc-unica-estructura-holding-cuando-como-cuesta": c71,
"mantenimiento-anual-llc-obligaciones": c72,
"modelo-720-721-residentes-espana-cuentas-cripto-extranjero": c73,
"modulos-vs-estimacion-directa-2026": c74,
"nomada-digital-residencia-fiscal": c75,
"nuevo-mexico-vs-wyoming-vs-delaware": c76,
"operating-agreement-llc-que-es": c77,
"pagar-cero-impuestos-legalmente-llc": c78,
"pasarelas-pago-llc-stripe-paypal-dodo": c79,
"por-que-abrir-llc-estados-unidos-ventajas": c80,
"por-que-no-abrir-empresa-estonia": c81,
"prevencion-blanqueo-capitales-llc": c82,
"primer-mes-llc-que-esperar": c83,
"privacidad-llc-americana-secreto-ventaja": c84,
"problemas-comunes-llc-como-evitarlos": c85,
"que-es-irs-guia-duenos-llc": c86,
"que-pasa-si-no-presentas-5472-multas-irs": c87,
"recuperar-llc-boi-5472-atrasados-procedimiento": c88,
"registered-agent-que-es-por-que-necesitas": c89,
"reorganizar-banca-llc-mercury-relay-wise": c90,
"residentes-no-residentes-llc-diferencias": c91,
"retenciones-irpf-factura": c92,
"revolut-business-crs-reporting-fiscal": c93,
"riesgos-fiscales-mala-estructuracion-internacional": c94,
"separar-dinero-personal-llc-por-que-importa": c95,
"single-member-multi-member-llc-implicaciones-fiscales": c96,
"sociedad-limitada-espana-costes-ventajas": c97,
"tengo-llc-checklist-gestion-correcta": c98,
"testaferros-prestanombres-llc-ilegal-riesgos": c99,
"tiempos-pagos-ach-wire-transfer": c100,
"tramos-irpf-2026": c101,
"tributacion-llc-segun-actividad-economica": c102,
"tributacion-pass-through-llc-como-funciona": c103,
"vender-o-cerrar-llc-comparativa-practica": c104,
"ventajas-desventajas-llc-no-residentes": c105,
"visa-mastercard-reporting-tarjetas-hacienda": c106,
"w8-ben-y-w8-ben-e-guia-completa": c107,
"wise-bancos-llc-stack-bancaria-completa": c108,
"wise-business-crs-reporting-fiscal": c109,
"wise-business-llc-guia": c110,
"wise-iban-llc-que-reporta-hacienda": c111,
};
